db:
  image: postgres:9.4
  restart: always
  expose:
    - 5432
  environment:
    POSTGRES_USER: "editor"
    POSTGRES_PASSWORD: "N0A8KHWWHMjRBTrc8UjL"
editor:
  image: services-toolkit/editor
  ports:
   - "40001:8080"
  links:
    - db
    - engine
  environment:
    POSTGRES_USER: "editor"
    POSTGRES_PASSWORD: "N0A8KHWWHMjRBTrc8UjL"
    ENGINE_HOST: "engine"
    ENGINE_PORT: "8080"
engine:
  image: services-toolkit/engine
  expose:
   - 8080
  ports:
   - "40000:8080"
